/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104731-g4a6aece703-20211202"
#endif /* AVUTIL_FFVERSION_H */
